### ISSUE TITLE
Фейлітся на node 16 +

### ISSUE THREAD

**Issue by dagolinuxoid** [Archakov06/react-sneakers#1]
Это ішью реторіческое (чісто для рефренса) но оставляю его тут в случае еслі другіе пограммісты столкнутся с такой проблеммой і не смогут локально развернуть кроссовочное пріложеніе. У меня с установленной 16 нодой вылетала ошібка во время процессінга npm install і проект не собірался. Решілось с переходом на 14 lts версію node js.

**Comment by icecoveredjune** [comment]
И в package,json заменить homepage на ".", чтобы пути к изображениям не ломались.
